### ISSUE TITLE
python errors in release v0.4.0

### ISSUE THREAD

**Issue by leefernandes** [ticketmaster/rules_opa#19]
with @rules_python version `e7b51d7e557a2a5a244c58a81f77b5ab090f4973`

```shell
Traceback (most recent call last):
  File "/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_opa/tools/opa_ctx.runfiles/rules_opa/tools/opa_ctx.py", line 10, in <module>
    class Args:
  File "/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_opa/tools/opa_ctx.runfiles/rules_opa/tools/opa_ctx.py", line 11, in Args
    output: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by leefernandes** [comment]
I suppose this is a python version incompatibility, where do we identify which python version @rules_opa depends on?

**Comment by ffortier** [comment]
3.11 but I can make it compatible with less than that if required.
